{
 "title": "Form Builder",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "platform_env", "query": "test,integration,live" },
   { "name": "deployment_env", "query": "dev,staging,production" }
  ]
 },
 "panels": [
  { "title": "Submitter Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Failed Submitter Resque Jobs",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resque_jobs_failed{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"})"
    }
   ]
  },
  {
   "title": "Pending Submitter Resque Jobs",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resque_jobs_pending{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"})"
    }
   ]
  },
  {
   "title": "Processed Submitter Resque Jobs",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resque_jobs_processed{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"})"
    }
   ]
  },
  { "title": "Namespace Quotas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Forms Namespace Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Platform Namespace Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Forms Namespace CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-services-$platform_env-$deployment_env\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(container_spec_cpu_quota{namespace=\"formbuilder-services-$platform_env-$deployment_env\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Platform Namespace CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(container_spec_cpu_quota{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  { "title": "Cloud Platform", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Platform Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\",pod_name!~\"fb-av-.*\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Platform Memory Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}) by (pod)"
    }
   ]
  },
  {
   "title": "ClamAV Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"formbuilder-platform-$platform_env-$deployment_env\",pod_name=~\"fb-av-.*\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "ClamAV CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-platform-$platform_env-$deployment_env\",pod_name=~\"fb-av-.*\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Forms Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Forms Memory Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_memory_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(container_memory_usage_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\",container_name!=\"\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_memory_bytes{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Platform CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-platform-$platform_env-$deployment_env\",pod_name!~\"fb-av-.*\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Platform CPU Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"formbuilder-platform-$platform_env-$deployment_env\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Forms CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod_name)"
    }
   ]
  },
  {
   "title": "Forms CPU Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_requests_cpu_cores{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod)"
    },
    {
     "expr": "sum(label_replace(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}, \"pod\", \"$1\", \"pod_name\", \"(.*)\")) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{namespace=\"formbuilder-services-$platform_env-$deployment_env\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Platform Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='formbuilder-platform-$platform_env-$deployment_env'}[5m]))))",
     "legendFormat": "Platform Bytes Received (Avg)"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='formbuilder-platform-$platform_env-$deployment_env'}[5m]))))",
     "legendFormat": "Platform Bytes Transmitted (Avg)"
    }
   ]
  },
  {
   "title": "Forms Network",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_receive_bytes_total{namespace='formbuilder-services-$platform_env-$deployment_env'}[5m]))))",
     "legendFormat": "Form Bytes Received (Avg)"
    },
    {
     "expr": "sort_desc(avg(sum by (pod_name) (rate(container_network_transmit_bytes_total{namespace='formbuilder-services-$platform_env-$deployment_env'}[5m]))))",
     "legendFormat": "Form Bytes Transmitted (Avg)"
    }
   ]
  },
  {
   "title": "Form Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace=\"formbuilder-services-$platform_env-$deployment_env\"}[5m])"
    }
   ]
  },
  {
   "title": "Form duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(rate(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"formbuilder-services-$platform_env-$deployment_env\"}[5m]) / rate(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"formbuilder-services-$platform_env-$deployment_env\"}[5m]) > 0) by (ingress)"
    }
   ]
  },
  {
   "title": "Form HTTP Codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{exported_namespace = \"formbuilder-services-$platform_env-$deployment_env\"}[5m])) by (status)"
    }
   ]
  }
 ]
}